defmodule WalEx.Event.Dsl do
  @moduledoc """
  Macros that build the `process_all/process_insert/process_update/process_delete`
  callbacks invoked by `WalEx.Events.EventModules` for each subscribed table.

  Used by host applications via `use WalEx.Event, name: MyApp`. The `on_event/2`,
  `on_insert/4`, `on_update/4`, and `on_delete/4` macros expand into the
  appropriate `process_*` functions on the host module.
  """

  # The macros below intentionally build deeply-nested quote blocks (event ->
  # function -> case -> task). Refactoring would require shipping additional
  # helper macros and obscures the generated code more than it simplifies.
  # credo:disable-for-this-file Credo.Check.Refactor.Nesting

  @doc """
  Fans `events` out to each function in `functions`, running them in independent
  `Task`s. Each function may be an atom (a function in the caller's module) or a
  `{Module, function}` tuple.
  """
  defmacro process_events_async(events, functions) do
    [module | _] = __CALLER__.context_modules

    quote do
      Enum.each(unquote(events), fn event ->
        unquote(functions)
        |> Enum.each(fn function ->
          task_fn =
            case function do
              # If function is a tuple, treat it as {Module, function}
              {mod, func} when is_atom(mod) and is_atom(func) ->
                fn -> apply(mod, func, [event]) end

              # If function is an atom, treat it as a local function in the current module
              # maybe don't allow atoms
              func when is_atom(func) ->
                fn -> apply(unquote(module), func, [event]) end

              _ ->
                raise ArgumentError, "Invalid function: #{inspect(function)}"
            end

          Task.start(task_fn)
        end)
      end)
    end
  end

  @doc """
  Defines `process_all/1` on the caller module.

  With `:all`, the block receives every event in the transaction. With a table
  name, the block receives only events for that table after applying
  `filters` (`:unwatched_records`, `:unwatched_fields`) and dispatching to
  `functions`.
  """
  defmacro on_event(:all, do_block) do
    quote do
      @doc "Auto-generated by `on_event(:all, ...)`; invoked with every event in the transaction."
      def process_all(txn) do
        case filter_events(txn) do
          filtered_events when is_list(filtered_events) and filtered_events != [] ->
            unquote(do_block).(filtered_events)

          _ ->
            {:error, :no_events}
        end
      end
    end
  end

  @doc "Defines `process_all/1` for a specific table; same shape as `on_insert/4` but matches every event type."
  defmacro on_event(name, filters \\ %{}, functions \\ [], do_block) do
    quote do
      @doc "Auto-generated by `on_event/4`; filters the transaction to the configured table before invoking the block."
      def process_all(txn) do
        case filter_events(txn, unquote(name), unquote(nil), unquote(filters)) do
          filtered_events when is_list(filtered_events) and filtered_events != [] ->
            process_events_async(filtered_events, unquote(functions))
            unquote(do_block).(filtered_events)

          _ ->
            {:error, :no_events}
        end
      end
    end
  end

  defp process_event(name, type, filters, functions, do_block) do
    quote do
      def unquote(:"process_#{type}")(txn) do
        case filter_events(txn, unquote(name), unquote(type), unquote(filters)) do
          filtered_events when is_list(filtered_events) and filtered_events != [] ->
            process_events_async(filtered_events, unquote(functions))
            unquote(do_block).(filtered_events)

          _ ->
            {:error, :no_events}
        end
      end
    end
  end

  @doc "Defines `process_insert/1` on the caller for events on `name` matching `filters`."
  defmacro on_insert(name, filters \\ %{}, functions \\ [], do_block) do
    process_event(name, :insert, filters, functions, do_block)
  end

  @doc "Defines `process_update/1` on the caller for events on `name` matching `filters`."
  defmacro on_update(name, filters \\ %{}, functions \\ [], do_block) do
    process_event(name, :update, filters, functions, do_block)
  end

  @doc "Defines `process_delete/1` on the caller for events on `name` matching `filters`."
  defmacro on_delete(name, filters \\ %{}, functions \\ [], do_block) do
    process_event(name, :delete, filters, functions, do_block)
  end
end
